version: '3'
services:
  haraajudb:
    image: postgres:12
    volumes:
      - haraaju-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
     POSTGRES_DB: haraaju-db
     POSTGRES_USER: haraaju-admin
     POSTGRES_PASSWORD: 1nf0M@t1cs
    networks:
     - docker-network
  webui:
    image: haraaju-ui:latest
    ports:
    - '4200:80'
    networks:
     - docker-network

  # api:
  #   image:  api-gateway:latest
  #   ports:
  #   - '9000:9000'
  #   networks:
  #   - docker-network
  #   depends_on: 
  #   - consul
      
  itemservice:
    image:  itemservice:latest
    ports:
    - '8080:8080'
    depends_on: 
    - consul
    - haraajudb
    networks:
     - docker-network
      
  consul:
    image: bitnami/consul:1
    volumes:
      - consul_data:/bitnami/consul
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
    networks:
     - docker-network

volumes:
  haraaju-db-data:
  consul_data:

networks:
  docker-network:
    driver: bridge